### ISSUE TITLE
Remove `ensure_omnistaging` for newer versions of jax

### ISSUE THREAD

**Issue by shyams2** [mpi4jax/mpi4jax#154] opened 2022-07-29 18:01 UTC
It seems like the current version of `mpi4jax` isn't compatible with the latest version of jax (0.3.15). In particular, it seems like they've removed the `omnistaging_compatible` attribute of `jax.config`.

I've managed to trace down [the commit](https://github.com/google/jax/commit/dbae3e5ed15bdacd5c535fc75550e54b33c75d7e) which removed this functionality. From what I can see, there's no point in having `ensure_omnistaging` function anymore.

**Comment by dionhaefner** [comment] 2022-07-29 19:44
Thanks for letting us know. This is already addressed in #151, which is blocked at the moment due to a regression in JAX 0.3.15. For now, JAX 0.3.15 is incompatible with `mpi4jax`. Please downgrade to 0.3.14.

**Closed by dionhaefner** 2022-07-29 19:44 UTC

**Comment by jjlow** [comment] 2022-08-04 18:43
I am having the same issue with jax[GPU].  When I try the command "pip install jax[gpu]==0.3.14", I get the warning "jax 0.3.14 does not provide the extra 'gpu'".  Which version of jax[GPU} should I install to be compatible with mpi4jax?

**Comment by PhilipVinc** [comment] 2022-08-04 18:48
Please have a look at the official jax documentation https://github.com/google/jax#pip-installation-gpu-cuda

The command you are using is outdated, there's a new one.

**Comment by jjlow** [comment] 2022-08-04 19:54
Thank you for that suggestion.  I used the command "pip install "jax[cuda11_cudnn82]==0.3.14" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html" which worked.

However, Now I get an error that generates the following error. 

"cudaStreamSynchronize failed with the following error:
	Error 2 cudaErrorMemoryAllocation: out of memory" 

and warnings about "Not using CUDA-enabled MPI" which is not true.  Do have any suggestions on how I could solve this issue?

**Comment by dionhaefner** [comment] 2022-08-05 10:51
For the OOM errors you will probably need to [prevent JAX from gobbling up all GPU memory](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html) (MPI needs some space to operate). For example by setting

```bash
$ export XLA_PYTHON_CLIENT_MEM_FRACTION=.80  # or even lower
```

Regarding the warning, please [see our docs](https://mpi4jax.readthedocs.io/en/latest/sharp-bits.html#using-cuda-mpi).
